### PR TITLE
Added fpdf to libs comparison table

### PR DESCRIPTION
**Pull request by Lucas-C**
Preview: https://github.com/Lucas-C/pikepdf/tree/patch-1#features

### CODE REVIEW

**Comment by dreua** [comment]
Can this library actually read PDFs or only generate them? Generating PDFs is cool but not really comparable to those libraries that can read and write imo. At least it should be noted somewhere.

**Comment by Lucas-C** [comment]
Good point.
No, `fpdf` is aimed at generating PDFs.
It cannot open/parse/read an existing one.

**Comment by Lucas-C** [comment]
Closing this then :)

**Comment by dreua** [comment]
Note that I'm not pikepdf developer, I just asked out of curiosity and stated my opinion as a user.

**Pull request closed without merging**
