### PR TITLE
fix and format by ruff

### PR DESCRIPTION
**Pull request by YoshitakaNaraoka**
As the title says

### CODE REVIEW

**Comment by jbarlow83** [comment]
pikepdf uses single quotes for internal strings, and double quotes for user visible strings like error messages. I find the distinction helpful and would prefer not to remove it; also, it would create a bunch of conflicts on development branches.

If you're interested in helping switch from black to ruff formatting, please redo with
`quote-style = preserve`
which was recently introduced to ruff in https://github.com/astral-sh/ruff/pull/8822, and then update pyproject.toml to drop black.

**Comment by jbarlow83** [comment]
quote-style = preserve is apparently a preview only feature meaning it can't be properly enabled in IDEs, so it's not ready for merging after all.

**Comment by jbarlow83** [comment]
I will merge it again when quote-style = preserve is available in the charliermarsh.ruff VS Code plugin and latest ruff version.

**Comment by YoshitakaNaraoka** [comment]
okay

**Pull request merged**
