### PR TITLE
Don't assume filter_decodeparms[0][1] is always set. Use defaults if set to None

### PR DESCRIPTION
**Pull request by kraptor**
I came across some PDF files that were failing because the retrieved values were None, so .get() was failing.

Added a check against None and used defaults in that case. Not sure if it's the best solution.

### CODE REVIEW

**Comment by kraptor** [comment]
I think CI failed but it's not related to the changes. Any idea?

**Comment by jbarlow83** [comment]
Very likely due to an unrelated issue - see commit e537b81f.
If there's still an issue please try rebasing on to master.

**Comment by jbarlow83** [comment]
Please rebase onto master.

**Comment by mara004** [comment]
@kraptor ?

**Pull request merged**
